detectors:
  Attribute:
    enabled: false
    exclude: []
  BooleanParameter:
    enabled: true
    exclude: []
  ClassVariable:
    enabled: false
    exclude: []
  ControlParameter:
    enabled: true
    exclude: []
  DataClump:
    enabled: true
    exclude: ['CodeClimateApiMocker']
    max_copies: 2
    min_clump_size: 2
  DuplicateMethodCall:
    enabled: true
    exclude: ['GithubService#handle_event',
              'EventBuilders::Review#assign_attrs',
              'EventsProcessor::ReviewBuilder#self.assign_attrs']
    max_calls: 1
    allow_calls: []
  FeatureEnvy:
    enabled: false
    exclude: []
  InstanceVariableAssumption:
    enabled: false
  IrresponsibleModule:
    enabled: false
    exclude: []
  LongParameterList:
    enabled: true
    exclude: ['WordpressApiMocker#stub_single_blog_post_response',
              'CodeClimate::RepositorySummary', 
              'CodeClimate::RepositoriesSummary']
    max_params: 4
    overrides:
      initialize:
        max_params: 5
  LongYieldList:
    enabled: true
    exclude: []
    max_params: 3
  ManualDispatch:
    enabled: true
    exclude: []
  MissingSafeMethod:
    enabled: false
    exclude: []
  ModuleInitialize:
    enabled: true
    exclude: []
  NestedIterators:
    enabled: true
    exclude: []
    max_allowed_nesting: 2
  NilCheck:
    enabled: false
    exclude: []
  RepeatedConditional:
    enabled: true
    exclude: ['DevelopmentMetricsController']
    max_ifs: 3
  SubclassedFromCoreClass:
    enabled: true
    exclude: []
  TooManyConstants:
    enabled: true
    exclude: []
    max_constants: 5
  TooManyInstanceVariables:
    enabled: true
    exclude: ['DevelopmentMetricsController']
    max_instance_variables: 9
  TooManyMethods:
    enabled: true
    exclude: ['DevelopmentMetricsController']
    max_methods: 25
  TooManyStatements:
    enabled: true
    exclude:
      - initialize
    max_statements: 12
  UncommunicativeMethodName:
    enabled: true
    exclude: []
    reject:
      - "/^[a-z]$/"
      - "/[0-9]$/"
      - "/[A-Z]/"
    accept: []
  UncommunicativeModuleName:
    enabled: true
    exclude: []
    reject:
      - "/^.$/"
      - "/[0-9]$/"
    accept:
      - Inline::C
      - "/V[0-9]/"
  UncommunicativeParameterName:
    enabled: true
    exclude: []
    reject:
      - "/^.$/"
      - "/[0-9]$/"
      - "/[A-Z]/"
    accept: []
  UncommunicativeVariableName:
    enabled: true
    exclude: []
    reject:
      - "/^.$/"
      - "/[0-9]$/"
      - "/[A-Z]/"
    accept:
      - _
  UnusedParameters:
    enabled: true
    exclude: []
  UnusedPrivateMethod:
    enabled: false
  UtilityFunction:
    enabled: false

exclude_paths:
  - config
  - app/models/concerns/ransackable.rb
