review_turnaround_generator:
  cron: '30 23 * * *'
  class: 'ProcessReviewTurnaroundMetricsJob'

weekly_metrics:
  cron: '50 23 * * 1-5'
  class: 'WeeklyMetricsJob'

merge_time_generator:
  cron: '00 23 * * *'
  class: 'ProcessMergeTimeMetricsJob'
