code_owners_list:
  cron: '00 23 * * 1-5'
  class: 'CodeOwnersListJob'
  active_job: true

external_contributions_processor:
  cron: '00 5 * * 1-5'
  class: 'ExternalContributionsProcessorJob'
  active_job: true

jira_defect_metrics_updater:
  cron: '00 6 * * 1-5'
  class: 'JiraDefectMetricsUpdaterJob'
  active_job: true

open_source_metrics_update:
  cron: '00 6 * * *'
  class: 'OpenSourceMetricsUpdaterJob'
  active_job: true

organization_members_updater:
  cron: '00 5 * * 1-5'
  class: 'OrgUsersUpdaterJob'
  active_job: true

repositories_update:
  cron: '30 5 * * 6'
  class: 'RepositoriesImporterJob'
  active_job: true

send_open_source_notification:
  cron: '00 10 * * 5'
  class: 'OpenSourceSlackJob'
  active_job: true
