review_turnaround_generator:
  cron: '30 23 * * *'
  class: 'ProcessReviewTurnaroundMetricsJob'
  active_job: true

weekly_metrics:
  cron: '50 23 * * 1-5'
  class: 'WeeklyMetricsJob'
  active_job: true

merge_time_generator:
  cron: '00 23 * * *'
  class: 'ProcessMergeTimeMetricsJob'
  active_job: true

blog_posts_partial_update:
  cron: '00 4 * * 3'
  class: 'BlogPostsPartialUpdaterJob'
  active_job: true

blog_posts_full_update:
  cron: '00 2 1 * *'
  class: 'BlogPostsFullUpdaterJob'
  active_job: true

blog_metrics_partial_update:
  cron: '30 4 * * *'
  class: 'BlogMetricsPartialUpdaterJob'
  active_job: true

blog_metrics_full_update:
  cron: '00 3 1 * *'
  class: 'BlogMetricsFullUpdaterJob'
  active_job: true

code_owners_list:
  cron: '00 23 * * 1-5'
  class: 'CodeOwnersListJob'
  active_job: true

code_climate_metrics_update:
  cron: '00 * * * *'
  class: 'CodeClimateMetricsUpdaterJob'
  active_job: true
